### ISSUE TITLE
error on Transform data 

### ISSUE THREAD

**Issue by rdewijn** [tercen/Heatmap_Dashboard#11]
Crash / instabilities when pressing the "transform data" button in the operator view.
Seems related to issue #7 

I think this may result when pressing the "transform data" button without first pressing the main Run button of the cross-tab view in Tercen. Should this be possible at all?

**Comment by ginberg** [comment]
@rdewijn yes indeed, it's only possible to save data in "run" mode. If you are going to operator view, it's a view only mode. I have added a PR that fixes the crash
