### ISSUE TITLE
Sort by Correlate

### ISSUE THREAD

**Issue by Savi235** [tercen/Heatmap_Dashboard#13]
When we select a column factor (Eg Treatment) and try to sort rows by Correlation there is an erreor message.

Error: C stack usage 7970708 is too close to the limit
Execution halted

The following file was used:
https://tercen.com/PamgeneEvaluators/w/ebd643c3119c715cacdef627bbe12658/ds/04636eb8-225a-455f-8bf4-775f5f5f1a9f/wa

Thank you
Savi Dirk Peter

**Comment by ginberg** [comment]
@Savi235 the latest version of this operator is available for validation in the PamgeneEvaluators library
